all: decision_tree_id3

decision_tree_id3: decision_tree_id3.c decision_tree_id3.h
	gcc -g -lm -Wall -Wextra -o decision_tree_id3 decision_tree_id3.c decision_tree_id3.h

clean:
	rm decision_tree_id3
